### ISSUE TITLE
Changing background colour

### ISSUE THREAD

**Issue by srikarym** [openai/procgen#11]
Is there an easy way to change the background color of maps in fruitbot while keeping the rest of the objects same? Background color is one of the attributes that varies across levels. I'm trying to change it without having to manually modify the pixel values.

**Comment by christopherhesse** [comment]
You can set it to use whatever backgrounds you want here: https://github.com/openai/procgen/blob/master/procgen/src/games/fruitbot.cpp#L42

`topdown_backgrounds` is loaded here: https://github.com/openai/procgen/blob/master/procgen/src/resources.cpp#L108 so you can replace those filenames with the files you actually want to load.

**Comment by srikarym** [comment]
I installed procgen via pip. I cant find the cpp files in site-packages/procgen. Do I need to clone the repo, make those changes and reinstall procgen?

**Comment by srikarym** [comment]
I installed procgen via pip and I couldn't find the cpp files in site-packages/procgen. I was able to change the background by downloading the source and editing the cpp and running procgen from the source code folder because it is built and then executed. Is there a way I can pass an argument while creating the env from python, based on which a certain map is selected?

**Comment by christopherhesse** [comment]
I'm afraid there is no option for that.  You can add your own option if you want, game-level options should be parsed here: https://github.com/openai/procgen/blob/50b607bbad69282043a2cd42591016520ca9747f/procgen/src/game.cpp#L41

**Comment by christopherhesse** [comment]
And on the python side they are set here: https://github.com/openai/procgen/blob/master/procgen/env.py#L98

**Comment by srikarym** [comment]
This is helpful. Thanks
