### ISSUE TITLE
How to package custom environments?

### ISSUE THREAD

**Issue by zplizzi** [openai/procgen#14]
I have created a custom environment (which I can play interactively), and would like to be able to install and use it on machines that don't have the full conda/Qt/etc build setup. This works with the standard environments if I install procgen via pip, so I know it's possible. I tried building wheels by running `pip wheel .`, and then installing the wheels on the target machines (here just a different `pyenv` env). The wheel installs fine, but when trying to use it, I get this error:

```
% python -c "from procgen import ProcgenEnv; ProcgenEnv(num_envs=1, env_name='coinrun')"                                                                                             1 ↵
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/procgen/env.py", line 186, in __init__
    super().__init__(num_envs, env_name, options, **kwargs)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/procgen/env.py", line 118, in __init__
    lib_dir=lib_dir, num_envs=num_envs, debug=debug, options=options
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/procgen/libenv.py", line 94, in __init__
    self._c_lib = self._ffi.dlopen(name=self._lib_path, flags=dlopen_flags)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/cffi/api.py", line 146, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/cffi/api.py", line 828, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/cffi/api.py", line 823, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/procgen/build/libenv.so': /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/ubuntu/.pyenv/versions/miniconda3-3.7.0/envs/procgen/lib/./libpng16.so.16).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/procgen/build/libenv.so'
```

It seems like the wheel has links to my miniconda installation somehow, even though I'm trying to install it in a non-conda env. Unfortunately I'm not too familiar with how wheels work so I'm not sure where to go from here.

**Comment by zplizzi** [comment]
It seems to work after building+installing zlib 1.2.9 from source, still not sure exactly why that was required for my wheels and not for the default pip procgen wheels.

**Comment by twkillian** [comment]
Hey @zplizzi, this is far after the fact that you got this working... But, I'm curious to know more about your process? I'm trying to have my custom Procgen environments that are pre-compiled locally be able to work "out of the box" on a remote server by installing a locally built wheel (building on macOS and using in a Linux env.)

Any pointers or help would be greatly appreciated.
