### ISSUE TITLE
0.9.2:CMakeLists.txt and src directory not installed by pip

### ISSUE THREAD

**Issue by shinryujin** [openai/procgen#16]
On 2019 DEC28 (0.9.2) pip installation does have a slight issue to which I applied a workaround, is this normal?

**System Info:**
- OS: Ubuntu 18.04 bionic
- Shell: bash 4.4.20
- pip 19.2.3 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
- Note I am using a [tensorflow docker image](https://hub.docker.com/r/tensorflow/tensorflow/) with ssh/X11 forwarding already pre-enabled (i.e. on the base image I can play [lincity](https://packages.ubuntu.com/search?keywords=lincity) (a city builder game, NOT lincity-ng) on X11 forwarding)

**After having the base image setup, add packages specific to procgen:**
`# apt-get install libgl1 freeglut3 freeglut3-dev cmake qt5-default
`

**Below: steps to reproduce the problem**
`# pip install procgen
`
`# python -m procgen.interactive --env-name starpilot
`

output of running procgen.interactive:
```
building procgen...RUN FAILED ['cmake', '-G', 'Unix Makefiles', '-DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake', '../..', '-DCMAKE_BUILD_TYPE=relwithdebinfo']:
CMake Error: The source directory "/usr/local/lib/python3.6/dist-packages/procgen" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

workaround (with commands followed by messages)
`# git clone https://github.com/openai/procgen.git
`
`# cd procgen/procgen
`
`# cp CMakeLists.txt /usr/local/lib/python3.6/dist-packages/procgen
`
`# python -m procgen.interactive --env-name starpilot
`
```
building procgen...RUN FAILED ['cmake', '-G', 'Unix Makefiles', '-DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake', '../..', '-DCMAKE_BUILD_TYPE=relwithdebinfo']:
-- Configuring done
CMake Error at CMakeLists.txt:45 (add_library):
  Cannot find source file:

    src/assetgen.cpp
```
`# cp -r src/ /usr/local/lib/python3.6/dist-packages/procgen
`

Now I can run and play the game with normal output (arrow key sto move, s to shoot forwards)

`# python -m procgen.interactive --env-name starpilot
`
```
building procgen...done
done=0 steps=15 episode_steps=15 episode_return_delta=0.0 episode_return=0.0
...
done=1 steps=131 episode_steps=131 episode_return_delta=0.0 episode_return=0.0
final info={'episode_steps': 131, 'episode_return': 0.0, 'level_seed': 917172192, 'level_complete': 0}
```

Please let me know if there is a method to make installation go more smoothly through pip (without having to git clone this repository; without copying the CMakeLists.txt and src directory manually). Thank you for providing procgen.

**Comment by christopherhesse** [comment]
This is a bug in the procgen code which is supposed to detect if procgen is installed.  Thanks for all the information!  I was able to reproduce it with the following `Dockerfile`:

```
FROM tensorflow/tensorflow:2.1.0rc2-py3
RUN pip install procgen
RUN python -c 'import gym; env = gym.make("procgen:procgen-coinrun-v0"); print(env.reset())'
```

**Comment by christopherhesse** [comment]
This should be fixed in the next version of procgen.
