### ISSUE TITLE
Setting new seed before reset

### ISSUE THREAD

**Issue by MarcoMeter** [openai/procgen#21]
```
    def seed(self, seed=None):
        """
        Seed the environment, this isn't used by VecEnvs but is part of the Gym Env API
        """
```

Do we have to create a new environment if we want to specify a new seed for starting a new episode?

**Comment by christopherhesse** [comment]
Yeah.  In general, the seed management should happen inside the environment so you should not need to do this.  You can specify a range of level seeds to use via the options: https://github.com/openai/procgen#environment-options and you can provide your own `rand_seed` if you want level seed selection to be deterministic.

What is your use case here?

**Comment by MarcoMeter** [comment]
My use-case comprises a framework to support multiple diverse RL environments (ml-agents, Procgen, Atari,. ..).
Agents are trained on fixed training seeds.
Evaluation occurs once in a while on different seeds.

My issue is concerned with specifying the exact seed for each individual evaluation run.
For now I wrapped procgen to close and reopen the environment to enforce a specific seed.

**Comment by christopherhesse** [comment]
Thanks for the explanation.  Re-creating the environment is probably the preferred way for procgen, as the `seed()` method isn't supported (sorry if the code wasn't clear).

**Comment by bjuergens** [comment]
> beachte: am Ende muss getestet werden ob es ein memoryleak gibt

es gibt ein memory leak. Hier ein kurzes beispiel: 

![grafik](https://user-images.githubusercontent.com/4362465/102266024-31ab3180-3f18-11eb-8b13-db3c52b72bcf.png)

generiert mit

```
pip install memory_profiler
mprof run --multiprocess neuro_evolution_ctrnn/train.py --configuration configurations/procgen.json
mprof plot
```

Das wird insbesondere zum Problem, wenn viele kurze Evaluationen ausgeführt werden. Als ich 1000 timesteps mit 10 evaluation pro individuum gemacht habe, war alles ok. Als ich 100 timesteps mit 20 evaluationen gemacht habe, kam es zu problemen. 

Quickfix: reuse_env ausschalten. Für Procgen ist das kein Problem, weil die env sowieso ständig neu angelegt wird, aber bei den anderen envs kann das doof sein. 

Es kann vllt auch was mit dem singleton vom EpRunner zu tun haben.

**Comment by christopherhesse** [comment]
Could you file a new issue if this is a memory leak in procgen? Ideally a script that shows the leak using random agent would be ideal.

**Comment by bjuergens** [comment]
sorry, my mistake. 

I had multiple tabs open, and wrote this comment in the wrong tab

**Comment by MarcoMeter** [comment]
Hi @christopherhesse 
is it possible to set a seed for the random number generator, that is operating inside the Procgen environment?
It is not sufficient to set this `random.SystemRandom().seed(seed)` as well as `random.seed(seed)` and `np.random.seed(seed)`.

**Comment by luciferkonn** [comment]
> Hi @christopherhesse is it possible to set a seed for the random number generator, that is operating inside the Procgen environment? It is not sufficient to set this `random.SystemRandom().seed(seed)` as well as `random.seed(seed)` and `np.random.seed(seed)`.

Same question here. More specifically, if we set start_level to a seed number, will we always get the same environment (i.e. initial position and goal position)?

**Comment by luciferkonn** [comment]
Thank you for the detailed explanation!
