### ISSUE TITLE
Get the original image

### ISSUE THREAD

**Issue by Cranial-XIX** [openai/procgen#26]
Hi, I am wondering if there is an easy way to get the full resolution observation instead of the (64,64,3) observation from the environment? Really thank you very much in advance.

**Comment by cshesse** [comment]
You can use `env.render(mode="rgb_array")` for the higher resolution human observations, this is what the interactive script does.

**Comment by cshesse** [comment]
If you wish to change the resolution for training, you have to install from source and change this constant: https://github.com/openai/procgen/blob/74e912519ff3ba2c46a62ea4cf3cf1c9171e3dc6/procgen/src/game.h#L21

**Comment by Cranial-XIX** [comment]
Thank you very much!
