### ISSUE TITLE
Custom Level Sampling Distributions?

### ISSUE THREAD

**Issue by GNiendorf** [openai/procgen#28]
Is there any way to have a custom level sampling distribution (maybe in the form of a list of level numbers that gets sampled uniformly like [0, 3, 4, 4, 9, ...]) rather than just specifying the start level and number of levels?

**Comment by christopherhesse** [comment]
I'm afraid that is not supported in the current setup, we're not accepting contributions of this kind, but you could definitely add some sort of string option that gets sent to the C++ side, such as `level_seed_list="1,3,4,5"` that is split and then sampled from.

**Comment by christopherhesse** [comment]
That would likely involve changing this code here: https://github.com/openai/procgen/blob/master/procgen/src/vecgame.cpp#L235

There's already a function called `split()` for splitting strings on commas.

**Comment by GNiendorf** [comment]
Thank you for pointing me in the right direction!
