### ISSUE TITLE
UnicodeDecodeError when building procgen in Windows 10

### ISSUE THREAD

**Issue by ailuropoda0** [openai/procgen#29]
When I built _procgen_ from source, it failed with _UnicodeDecodeError_.

>   File "C:\Users\ailur\Documents\GitHub\procgen\procgen\build.py", line 35, in run
    return sp.run(cmd, stdout=sp.PIPE, stderr=sp.STDOUT, encoding="utf8")
  File "C:\Users\ailur\Anaconda3\lib\subprocess.py", line 490, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Users\ailur\Anaconda3\lib\subprocess.py", line 951, in communicate
    stdout = self.stdout.read()
  File "C:\Users\ailur\Anaconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 14: invalid start byte

It seems because Windows has a different encoding system with macOS or Linux.
I am running procgen on Python 3.7 on Windows 10(locale.getpreferredencoding() is 'cp949')
When I change the encoding from 'utf8' to 'mbsc' in line 35 at procgen\build.py, it works well.

**Comment by christopherhesse** [comment]
I'm not sure if we want to support non-unicode.  Does the program work if you do `CHCP 65001` in the console before running it?  I'm not familiar with how windows manages character encodings, so I'm not certain what encoding could be used in `build.py` that would work on all systems.

**Comment by ailuropoda0** [comment]
Thanks, @christopherhesse. The program works after executing `chcp 65001`.

**Comment by christopherhesse** [comment]
Good to know, I'm going to close this for now.  If someone comes up with a better solution that doesn't break the build for any utf8 systems, a PR for this would likely be accepted.
