### ISSUE TITLE
Noisy monitor files

### ISSUE THREAD

**Issue by sjtuytc** [openai/procgen#30]
The monitor file recorded during the training process is noisy when using MPI.
![image](https://user-images.githubusercontent.com/31123348/74567845-b1592000-4f44-11ea-9e84-ddf7719bcc78.png)

**Comment by sjtuytc** [comment]
How to deal with that?

**Comment by christopherhesse** [comment]
I don't believe that procgen creates monitor files, what are you using to create these?

**Comment by sjtuytc** [comment]
I wrap the vecenv with gym monitor api to create monitor files.

**Comment by christopherhesse** [comment]
I don't think the gym monitor api supports vecenvs, are you use VecMonitor?  Could you provide a short example script that illustrates the problem?

**Comment by christopherhesse** [comment]
Most likely you are logging to the same filename from multiple ranks, you should make sure that each rank logs to a unique filename, such as `f"monitor{MPI.COMM_WORLD.rank}.csv"`

**Comment by sjtuytc** [comment]
Thanks, I got it! It solved my problem.
