### ISSUE TITLE
Get the locations of each object

### ISSUE THREAD

**Issue by kaixin96** [openai/procgen#32]
Is there any C++ api to get the locations (internal state) of each object (e.g. coin, agent, saw  in `coinrun`)? 

Thank you.

**Comment by christopherhesse** [comment]
I'm afraid there is no API for that.  I experimented with a "save state" feature, but it serialized the state into a string that can only be interpreted directly by the C++ code.

If you want to do this, you can modify the "info_space" to put information in the info dictionary returned by the gym API.  There is actually already some game information in this dictionary: https://github.com/openai/procgen/blob/master/procgen/src/vecgame.cpp#L300

Once you define an info space there, you can put information into it like `level_complete` here: https://github.com/openai/procgen/blob/master/procgen/src/game.cpp#L154

For something like coinrun, you'd probably want to do that in https://github.com/openai/procgen/blob/master/procgen/src/games/coinrun.cpp#L492, so assuming you've defined a space like:

```c
    {
        struct libenv_space s;
        strcpy(s.name, "coin_x");
        s.type = LIBENV_SPACE_TYPE_BOX;
        s.dtype = LIBENV_DTYPE_FLOAT32;
        s.shape[0] = 1;
        s.ndim = 1,
        s.low.float32 = -1e9f;
        s.high.float32 = 1e9f;
        info_spaces.push_back(s);
    }
```

You'd probably want something like

```c
*(float*)(info_bufs[3]) = (float)(coin_x);
```

Note that the index `3` there is the index of the info space in the `info_spaces` vector, so you'll probably want to define constants so those don't get confusing.

Also I didn't see the `coin_x` value being saved, so you'd have to save it at https://github.com/openai/procgen/blob/master/procgen/src/games/coinrun.cpp#L405

**Comment by kaixin96** [comment]
Thanks a lot for your help !

**Comment by jordan-schneider** [comment]
@kaixin96 Did you ever end up implementing this? If so, would you mind uploading the code somewhere (e.g. in a fork)? I need the underlying state for a bunch of different environments in the python API and this seems like the first step.
