### ISSUE TITLE
Different rewards for destroying the same objects in Starpilot game

### ISSUE THREAD

**Issue by hasanferit** [openai/procgen#35]
In Starpilot game, there flying objects and the agent tries to explode them. The rewards obtained by exploding the two exact same kind of objects in a fixed level are different from each other. 

Is this because the rewards are determined stochastically? If yes, is there an option that I can fix rewards?
Also, how can I learn the reward arrangements in each game? I checked the paper and the README however I could not find anything useful.

**Comment by christopherhesse** [comment]
The exact rewards for the environments are defined only in the code.   There's a rough description for each environment in the paper, along with normalization constants in Appendix C that will give you a sense of the scale.  The code for any individual environment is not super complicated though, starpilot is here: https://github.com/openai/procgen/blob/master/procgen/src/games/starpilot.cpp and has only two references to `step_data.reward`.

I see only a fixed reward per enemy for that environment though.  Do you have a more specific example you could give me for this, like a video + log of step data?

**Comment by hasanferit** [comment]
Below I describe the exact scenario.
I create the environment in this way:    
    env = ProcgenEnv(num_envs=num_envs, env_name=args.env_name, num_levels=num_levels, start_level=args.start_level, distribution_mode=args.distribution_mode)
    env = VecExtractDictObs(env, "rgb")
    env = VecMonitor(venv=env, filename=None, keep_buf=100)
    env = VecNormalize(venv=env, ob=False)

I specify the model in this way:
    model = Model(policy=policy, ob_space=ob_space, ac_space=ac_space, nbatch_act=nenvs, nbatch_train=nbatch_train, nsteps=nsteps, ent_coef=ent_coef, vf_coef=0.5, max_grad_norm=0.5, comm=comm, mpi_rank_weight=mpi_rank_weight)
    model.load('path_to_trained_model')

Then I let the agent play the game:
    obs = env.reset() 
    while True:
        actions, _, _, _ = model.step(obs)
        time.sleep(0.3)
        obs, rew, done, info = env.step(actions)
        if rew > 0:  print(rew)
        episode_rew += rew
        env.render()
        if done:
            print('episode_rew={}'.format(episode_rew))
            episode_rew = 0

As you see I print non-zero reward for each action. This prints the following for destroying the first two same kind objects:
    [5.102847]
    [1.9697533]

[Here](https://drive.google.com/open?id=1vPQFLRlpWzJUKbe5pOkotdPU7K2-IB6o) I uploaded a video.

**Comment by christopherhesse** [comment]
Can you make sure to run it without `VecNormalize` and post the updated results?

**Comment by hasanferit** [comment]
Yes this solved the problem. Thanks!

But, [here](https://github.com/openai/train-procgen/blob/master/train_procgen/train.py) in `train_procgen` repository `VecNormalize` is used to create the environment (Line 65).

Is there any difference between creating environment like I did above or the following:

`env = gym.make('procgen:procgen-' + args.env_name + '-v0', num_levels=num_levels, start_level=args.start_level, distribution_mode=args.distribution_mode)`

Also if I have question about the paper (nothing to do with the code) should I open an issue?

**Comment by christopherhesse** [comment]
`ProcgenEnv` produces a `VecEnv` with a vectorized interface (number of environments can be greater than 1), `gym.make` produces a conventional `gym` environment.
