### ISSUE TITLE
The question on _allocate_dict_space() in libenv.py

### ISSUE THREAD

**Issue by ailuropoda0** [openai/procgen#41]
I have a question on __allocate_dict_space()_ in _libenv.py_
Is there any reason to allot ```arr.data[env_idx:]```(all data from env_idx to the last) to ```buffers``` instead of ```arr.data[env_idx:env_idx+1]```(data for env_idx)?
```
for space_idx, (name, space) in enumerate(dict_space.spaces.items()):
    actual_shape = (num_envs,) + space.shape
    arr = self._numpy_aligned(shape=actual_shape, dtype=space.dtype)
    result[name] = arr
    for env_idx in range(num_envs):
        buffers[space_idx * num_envs + env_idx] = self._ffi.from_buffer(
            arr.data[env_idx:]
        )
```

**Comment by christopherhesse** [comment]
Good catch!  In this case though it looks like the length is discarded when its assigned into the buffers variable, which is a list of void* pointers.  Are you seeing something different?

I'll fix the code upstream just for clarity regardless.

**Comment by ailuropoda0** [comment]
Oh, I see.
You mean ```self._ffi.from_buffer(arr.data[env_idx:])``` is equal to ```self._ffi.from_buffer(arr.data[env_idx:env_idx+1])``` because ```buffers[space_idx * num_envs + env_idx]``` is the pointer to ```arr.data[env_idx:]```?

**Comment by christopherhesse** [comment]
Yes, if I knew of a way to do `&arr.data[env_idx]` that would be the most clear, but I don't see how to write that more directly.

**Comment by christopherhesse** [comment]
Specifically, while `self._ffi.from_buffer(arr.data[env_idx:])` != `self._ffi.from_buffer(arr.data[env_idx:env_idx+1])`, once you assign them into buffers, they should be equal since the void * pointers have no length and so that must be discarded.

**Comment by ailuropoda0** [comment]
Thanks for your answer.
I think the current code is okay.
I was confused because I am unfamiliar with the 'buffer' concept in Python.

**Comment by christopherhesse** [comment]
memoryviews and buffers are both very confusing and poorly documented
