### ISSUE TITLE
How do you get the last observation in an episode?

### ISSUE THREAD

**Issue by tkyaaida** [openai/procgen#44]
How do you get the last observation in an episode?
For example,
```
rew0, obs0, first0 = env.observe()
act = agent.policy(obs0)
env.act(act)
rew1, obs1, first1 = env.observe()
```
In my understanding, the agent receives obs0 and returns the action `act`. The environment goes to the next step and returns reward `rew1` and the next observation `obs1`.
My question is when `first1[i]` is True, `obs1['rgb'][i, :, :, :]` is the observation from the new episode instead of the last observation in the previous episode.

**Comment by christopherhesse** [comment]
I'm afraid that observation isn't returned due to the automatic reset.   What did you need that observation for?

Also, from the gym3 docs, I think your indexes are off a bit:
```
env = Env()
        # initial reward is ignored; didn't depend on actions
        _reward, ob_0, first_0 = env.observe()
        env.act(ac_0)
        reward_0, ob_1, first_1 = env.observe()
        env.act(ac_1)
```

**Comment by tkyaaida** [comment]
For (most) model-free methods, I don't think we need the last observation in the episode; Just saving "fake" transition tuple `(ob_0, ob_1, ac_0, reward_0, first_1)` into the buffer is fine because `ob_1` won't be used to calculate the target value.
However, for model-based methods, I think we need the last observation in the episode for learning a dynamics model. `ob_0[i]` to `ob_1[i]` is not the actual transition of the environment when `first_1[i]` is True. In that case, we would have to just discard the last (potentially very meaningful) transition.

**Comment by christopherhesse** [comment]
For model based methods, if you're modeling `ob_0, ac_0` to predict `ob_1, reward_0` (all from the same episode), when does correctly modeling `ob_1` matter provided it's an observation derived from a terminal state?  Like what's the difference between having `ob_1` be some dummy observation like all zeros or re-using `ob_0` in that case versus having the true `ob_1` value?

There is some information being discarded there, it's just unclear to me how important that information is for model-based methods.

**Comment by tkyaaida** [comment]
Okay, I understand this design choice. Maybe just using some dummy `ob_1` is good enough in practice. But it's still losing some information in the env side and I'm not sure whether the true terminal state won't matter at all in every single learning algorithm. Also, isn't it easy to pass the true terminal state as an additional key-value pair in obs? For example, how about adding 'terminal_state' key whose value is a numpy array that has the true terminal state for some indices and zeros elsewhere?

**Comment by christopherhesse** [comment]
Yeah, the true terminal observation could be included as an aux obs or in the info dict.  I think we would consider adding that for procgen if there was a concrete use case for it.
