### ISSUE TITLE
FileNotFoundError for gym3/internal/font.bin

### ISSUE THREAD

**Issue by GusHebblewhite** [openai/procgen#45]
Hi there :)

So I tried following the 'build from source' instructions, and I noticed that when I got to the last step (running the environment interactively with `python -m procgen.interactive`) I get an error message saying that 'gym3/internal/font.bin' is not found. 

This was an issue in gym3 (https://github.com/openai/gym3/issues/1) which is now fixed, but since this still uses gym3 0.3.0 the issue will remain here until it gets updated.

If anyone has the same problem in the meantime, building (the newest version of) gym3 manually seems to have fixed it.

Best,
Gus

**Comment by christopherhesse** [comment]
My bad, I forgot to update the pinned version.  Should be updated now: https://github.com/openai/procgen/commit/21f9ab656f5274ebda3e7bba3e19674c64334056

Thanks for letting me know!
