### ISSUE TITLE
Selecting specific levels

### ISSUE THREAD

**Issue by henrikmarklund** [openai/procgen#50]
Say I want to progressively add more levels to my train set. Is the easiest way to just reinitialize the environment, everytime I want to add new levels?

env = ProcGenEnv(num_levels=10, start_level=0)
env = ProcGenEnv(num_levels=20, start_level=0)
...
env = ProcGenEnv(num_levels=500, start_level=0)

And as my test set I have;
test_env = ProcGenEnv(num_levels=500, start_level=500)

Thanks,
Henrik

**Comment by MarcoMeter** [comment]
Yes, but I'd call `env`.close() first before re-initialization.

**Comment by henrikmarklund** [comment]
Excellent! Thank you!
