### ISSUE TITLE
Packaging custom environments for use in train-procgen repo

### ISSUE THREAD

**Issue by max-reuter** [openai/procgen#55]
As someone less familiar with packaging, I'm having trouble getting started with porting my custom environments such that I can train them using the `train-procgen` repo's code. [This issue](https://github.com/openai/procgen/issues/14#issue-541064428) seems to be the closest post to my problem. I've opened a [similar issue in the `train-procgen` repo.](https://github.com/openai/train-procgen/issues/15#issue-692029341)

I'd appreciate any instructions or tips for getting started.

**Comment by christopher-hesse** [comment]
If you want to create a binary wheel of procgen, I'd suggest using the existing travis CI configuration: https://github.com/openai/procgen/blob/master/.travis.yml which you may want to get running on a local machine first.

A github actions version would be nice, but I haven't had time to port it to github actions.

**Comment by max-reuter** [comment]
Solved by putting the `train_procgen` directory in my `procgen` directory (clone of this repo); then, running the training commands in the `train-procgen` repo automatically rebuilds based on the contents of my edited environments in my `procgen` directory, using them during training. Thanks @christopher-hesse!
