### ISSUE TITLE
About the full distribution of levels

### ISSUE THREAD

**Issue by Jonarain** [openai/procgen#56]
Does "the full distribution of levels" equal to "num_level=0" ?
I can't find any definition from your paper or comments from your code. (If I missed, I'm sorry)

**Comment by christopher-hesse** [comment]
Yes, 0 or unset (which defaults to 0) should result in INT32_MAX levels: https://github.com/openai/procgen/blob/master/procgen/src/vecgame.cpp#L287 which is about 2 billion.

**Comment by christopher-hesse** [comment]
The README says "num_levels=0 - The number of unique levels that can be generated. Set to 0 to use unlimited levels."  Which is slightly inaccurate since it's not "unlimited", changing the docs to say "the full distribution of levels" may make more sense.

**Comment by Jonarain** [comment]
Thank you very much for your answer.

"changing the docs to say "the full distribution of levels" may make more sense."
Yes, I definitely agree. "unlimited" made me confused.

**Comment by dwyzzy** [comment]
> Yes, 0 or unset (which defaults to 0) should result in INT32_MAX levels: https://github.com/openai/procgen/blob/master/procgen/src/vecgame.cpp#L287 which is about 2 billion.

Hi! I hope to know whether it means that we have to train and test on all of the set having 2 billion levels, as the paper said, 'When evaluating sample efficiency, we train and test agents on the full distribution of levels in each environment' (If I missed something important, I'm sorry)

**Comment by christopherhesse** [comment]
I believe that means that each episode selects a random level from the 2 billion, not that all 2 billion are used since there should be fewer than 2 billion episodes.
