### ISSUE TITLE
[Bug] If statement rendermode is wrong

### ISSUE THREAD

**Issue by HadiSDev** [openai/procgen#63]
in env.py we have:

```
        if render_mode is None:
            render_human = False
        elif render_mode == "rgb_array":
            render_human = True
        else:
            raise Exception(f"invalid render mode {render_mode}")
```

Should be the opposite

**Comment by christopherhesse** [comment]
I believe this is just a confusing name, and that `render_human` means to render a high resolution version of the scene, which is then used by the `render()` call with mode `rgb_array`.  If that's not the case please re-open this issue or file a new one.
