### ISSUE TITLE
Gym Environment Registry

### ISSUE THREAD

**Issue by AmrMKayid** [openai/procgen#7]
The environments are currently can't be found inside `envs.registry.all()`

**Comment by christopherhesse** [comment]
Are you sure you didn't forget to import the procgen package?  This is a confusing limitation of the gym API:

```
In [1]: import procgen

In [2]: import gym

In [3]: any(['procgen' in spec.id for spec in gym.envs.registry.all()])
Out[3]: True
```

The example in the README shows how to use `gym.make` without a manual import:

```
import gym
env = gym.make("procgen:procgen-coinrun-v0")
```

**Comment by AmrMKayid** [comment]
Ahaaa thank you, it's working now!
