### ISSUE TITLE
About the meaning of level

### ISSUE THREAD

**Issue by gemcollector** [openai/procgen#71]
I'm sorry I wanna ask 3 very simple questions: 
1. what does the "level" mean? Different levels have different visual background? 
2. So if I set up the "num_level=500" ,does that mean I will train an agent on 500 different visual background game? 
3. And how can I change to the generalization mode? just let the "num_level=0"?

Thx for your reply!~

**Comment by christopherhesse** [comment]
1) For many of the environments they don't have just different visual backgrounds, but also different maps (so like boxes in difference places, see coinrun for a good example)
2) Yeah, you can try this out with the interactive script, by setting `num_level=1` or `num_level=2`.
3) I believe that is correct.

**Comment by christopherhesse** [comment]
See also https://github.com/openai/procgen/issues/56
