### ISSUE TITLE
Do there exist any expert demonstrations?

### ISSUE THREAD

**Issue by albertcity** [openai/procgen#72]
I am curious about how to apply imitation learning in such a PCG environment. Do there exist any expert demonstrations?

**Comment by trancenoid** [comment]
I guess no, but I found a way to record : Use interactive mode, but replace `VideoRecorderWrapper` with `TrajectoryRecorderWrapper` in the `make_interactive` function.

Source : https://github.com/openai/gym3/blob/master/gym3/trajectory_recorder.py

**Comment by christopherhesse** [comment]
No, but agents can be trained that are pretty good at these environments, and you can record those agents playing.

**Comment by christopherhesse** [comment]
Thanks @trancenoid for the recording tip there.
