### ISSUE TITLE
Installing from source [Win10] [Anaconda]

### ISSUE THREAD

**Issue by trancenoid** [openai/procgen#75]
I noticed a peculiarity while installing procgen as mentioned in Readme.md
1) `pip install procgen` doesn't work for some reason on python 3.9.6 (conda)
2) conda needs to be on "PATH" in windows for the `python -c from procgen import ProcgenGym3Env; ProcgenGym3Env(num=1, env_name='coinrun')` to succeed

**Comment by christopherhesse** [comment]
1) There are no wheels for 3.9, if the CI works it may be easy to publish these soon
2) That makes sense, I'd accept a PR to clarify the docs or improve the error message

**Comment by christopherhesse** [comment]
Going to close this since there should be 3.9 wheels, feel free to file a new issue if there are other issues.
