### ISSUE TITLE
"Hakenkreuz" seed in maze environment

### ISSUE THREAD

**Issue by MarcoMeter** [openai/procgen#9]
Hello guys,

while just playing each environment interactively, I came a cross an inappropriate seed showing a "Hakenkreuz".

Seed: 741932422
Environment: Maze

Obviously this is just a coincident. So I just wanted to let you guys know about it.

(Tested on Windows 10)

**Comment by MarcoMeter** [comment]
![maze](https://user-images.githubusercontent.com/6996955/70691145-aa016600-1cb8-11ea-8052-b518bbf66ec4.png)

**Comment by kcobbe** [comment]
Ok, thanks for bringing this to our attention. We'll consider adding checks for this in a future version of the environment.
